# Generated by Django 4.2.28 on 2026-02-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение к посту', null=True, upload_to='posts_images', verbose_name='Изображение'),
        ),
    ]
